[package]
name = 'core-packages/react-devtools-shared'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1-rc.19'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
React = 'core-packages/react@17.0.1-rc.19'
ReactDebugTools = 'core-packages/react-debug-tools@17.0.1-rc.19'
ReactIs = 'core-packages/react-is@17.0.1-rc.19'
ReactReconciler = 'core-packages/react-reconciler@17.0.1-rc.19'
ReactRoblox = 'core-packages/react-roblox@17.0.1-rc.19'
Shared = 'core-packages/shared@17.0.1-rc.19'
