[package]
name = 'core-packages/react-debug-tools'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1-rc.19'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
ReactReconciler = 'core-packages/react-reconciler@17.0.1-rc.19'
Shared = 'core-packages/shared@17.0.1-rc.19'
