name: Fast-follow

on:
  workflow_dispatch:
  schedule:
    # Scheduled to run every day at 8am UTC.
    - cron: "0 8 * * *"

jobs:
  fast-follow:
    name: Runs fast-follow
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout js-to-lua
        uses: actions/checkout@v3
        with:
          path: js-to-lua-action
          repository: roblox/js-to-lua

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: downstream-repository

      - name: Set up GitHub identity
        run: |
          git config --global user.name github-actions
          git config --global user.email github@users.noreply.github.com

      - name: Run Fast Follow
        uses: ./js-to-lua-action/.github/actions/fast-follow
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          repo-path: downstream-repository

          pr-description-cc-users: "@grilme99"
